/* Seoul Dex — curated dataset.
 * Coordinates are approximate landmark centers; the app also links out to
 * Naver / Kakao / Apple Maps by name, so precision is not critical.
 * cat: sight | food | culture | nature | shopping | nightlife  (primary — sets card color)
 * tags: cross-cutting filters — "photo" (Instagrammable), "street" (street food),
 *       "booking" (needs an advance reservation)
 * rarity: common | rare | legendary  (Pokédex flavor)
 * hours: { o:"09:00", c:"18:00", x:[weekdays closed 0=Sun..6=Sat] }  or { always:true }
 *        (c < o means it closes after midnight). Hours are approximate — confirm before a long trip.
 * meal (food/nightlife): "lunch" | "dinner" | "both" | "coffee"
 * pick + why: a hand-picked highlight recommendation.
 */
window.SEOUL_HOME = { n: "Hotel Riviera", kr: "리베라호텔", lat: 37.5192, lng: 127.0480,
  area: "Cheongdam, Gangnam", subway: "Cheongdam (L7) · Exit 13" };

/* ICML / COEX convention venue — used by the "Food near the conference" mode. */
window.SEOUL_CONF = { n: "COEX / ICML", kr: "코엑스", lat: 37.5121, lng: 127.0590,
  area: "Samseong, Gangnam", subway: "Samseong (L2) · Exit 5-6" };

window.SEOUL_PLACES = [
  // ---------- Palaces & landmarks (sight) ----------
  { id: "gyeongbokgung", n: "Gyeongbokgung Palace", kr: "경복궁", cat: "sight", emoji: "🏯", lat: 37.5796, lng: 126.9770,
    area: "Jongno", subway: "Gyeongbokgung (L3) · Exit 5", rarity: "legendary", tags: ["photo"],
    hours: { o: "09:00", c: "18:00", x: [2] }, pick: true, why: "Seoul's grandest palace + the guard-changing ceremony",
    blurb: "Joseon dynasty's grand main palace (1395). The postcard of Seoul.",
    tip: "Free guard-changing ceremony ~10:00 & 14:00. Rent a hanbok nearby for free entry & photos. Closed Tuesdays." },
  { id: "changdeokgung", n: "Changdeokgung & Secret Garden", kr: "창덕궁", cat: "sight", emoji: "🍃", lat: 37.5794, lng: 126.9910,
    area: "Jongno", subway: "Anguk (L3) · Exit 3", rarity: "rare", tags: ["photo", "booking"],
    hours: { o: "09:00", c: "18:00", x: [1] }, pick: true, why: "UNESCO palace + the timed-entry Secret Garden",
    blurb: "UNESCO palace whose Huwon (Secret Garden) is the most serene spot in the old city.",
    tip: "BOOK AHEAD: the Secret Garden is timed-entry and sells out — reserve online. Closed Mondays." },
  { id: "deoksugung", n: "Deoksugung Palace", kr: "덕수궁", cat: "sight", emoji: "🏛️", lat: 37.5658, lng: 126.9751,
    area: "Jung-gu", subway: "City Hall (L1/L2) · Exit 2", rarity: "common",
    hours: { o: "09:00", c: "21:00", x: [1] },
    blurb: "Small palace blending Korean halls with Western-style stone buildings.",
    tip: "The stone-wall walk (돌담길) around it is a classic stroll. Open late. Closed Mondays." },
  { id: "nseoultower", n: "N Seoul Tower (Namsan)", kr: "N서울타워", cat: "sight", emoji: "🗼", lat: 37.5512, lng: 126.9882,
    area: "Namsan", subway: "Myeongdong (L4) → cable car", rarity: "legendary", tags: ["photo", "booking"],
    hours: { o: "10:00", c: "23:00" }, pick: true, why: "Sunset over the entire city skyline",
    blurb: "Seoul's skyline needle atop Namsan. Best at sunset into blue hour.",
    tip: "Book the observatory online to skip the queue. Take the cable car up; walk or bus down." },
  { id: "lotteworldtower", n: "Lotte World Tower · Seoul Sky", kr: "롯데월드타워", cat: "sight", emoji: "🌆", lat: 37.5125, lng: 127.1025,
    area: "Jamsil", subway: "Jamsil (L2/L8) · Exit 1-2", rarity: "legendary", tags: ["photo", "booking"],
    hours: { o: "10:00", c: "22:00" }, pick: true, why: "Glass-floor sky deck at 500m",
    blurb: "555m, Korea's tallest — glass-floor observation deck 'Seoul Sky' on floor 118.",
    tip: "BOOK a timed sunset slot online (cheaper + skips the line). Aquarium, mall & theme park at the base." },
  { id: "cheonggyecheon", n: "Cheonggyecheon Stream", kr: "청계천", cat: "sight", emoji: "💧", lat: 37.5696, lng: 126.9784,
    area: "Jung-gu", subway: "Gwanghwamun (L5) · Exit 5", rarity: "common", hours: { always: true },
    blurb: "Restored stream cutting through downtown — a cool, walkable escape from traffic.",
    tip: "Walk it east from Gwanghwamun after dark when the water is lit." },
  { id: "gwanghwamun", n: "Gwanghwamun Square", kr: "광화문광장", cat: "sight", emoji: "👑", lat: 37.5725, lng: 126.9769,
    area: "Jongno", subway: "Gwanghwamun (L5) · Exit 2", rarity: "common", hours: { always: true },
    blurb: "Civic heart of Seoul with statues of King Sejong and Admiral Yi Sun-sin.",
    tip: "Straight shot to Gyeongbokgung's gate — do both together." },
  { id: "seoullo", n: "Seoullo 7017 Skygarden", kr: "서울로7017", cat: "sight", emoji: "🌉", lat: 37.5560, lng: 126.9722,
    area: "Jung-gu", subway: "Seoul Station (L1/L4) · Exit 2", rarity: "common", tags: ["photo"], hours: { always: true },
    blurb: "A 1970s highway overpass reborn as an elevated garden-walkway of 24,000 plants above Seoul Station.",
    tip: "Best at dusk when it lights up blue. Great skyline photos toward Namsan." },

  // ---------- Neighborhoods & streets ----------
  { id: "bukchon", n: "Bukchon Hanok Village", kr: "북촌한옥마을", cat: "sight", emoji: "🏘️", lat: 37.5826, lng: 126.9849,
    area: "Jongno", subway: "Anguk (L3) · Exit 2", rarity: "rare", tags: ["photo"], hours: { always: true },
    pick: true, why: "Iconic hanok-rooftops-and-skyscrapers photo",
    blurb: "Hillside lanes of traditional hanok houses with the classic palace-tiles-and-skyscrapers photo.",
    tip: "People live here — keep quiet, visit 09:00–18:00. Go early for empty streets. The 'Bukchon 8 views' are signposted." },
  { id: "insadong", n: "Insadong", kr: "인사동", cat: "shopping", emoji: "🖌️", lat: 37.5740, lng: 126.9848,
    area: "Jongno", subway: "Anguk (L3) · Exit 6", rarity: "common", hours: { o: "10:00", c: "21:00" },
    blurb: "Antiques, tea houses, calligraphy, hanji paper and traditional crafts.",
    tip: "Duck into Ssamziegil, the spiraling craft mall. Great for gifts." },
  { id: "ikseondong", n: "Ikseon-dong Hanok Alley", kr: "익선동", cat: "food", emoji: "🏮", lat: 37.5741, lng: 126.9910,
    area: "Jongno", subway: "Jongno 3-ga (L1/3/5) · Exit 4", rarity: "rare", tags: ["photo"],
    hours: { o: "11:00", c: "23:00" }, meal: "dinner",
    blurb: "Old hanok blocks reborn as dense, photogenic cafés and cocktail bars.",
    tip: "Tiny and packed — best on a weekday evening. Every alley is a photo." },
  { id: "myeongdong", n: "Myeongdong", kr: "명동", cat: "shopping", emoji: "🛍️", lat: 37.5636, lng: 126.9850,
    area: "Jung-gu", subway: "Myeongdong (L4) · Exit 6", rarity: "common", tags: ["street"],
    hours: { o: "10:00", c: "22:00" }, meal: "dinner",
    blurb: "Cosmetics, fashion and a nightly street-food gauntlet: grilled cheese lobster, egg bread, tornado potato.",
    tip: "Come hungry after 18:00 when the food carts open." },
  { id: "hongdae", n: "Hongdae", kr: "홍대", cat: "nightlife", emoji: "🎸", lat: 37.5563, lng: 126.9236,
    area: "Mapo", subway: "Hongik Univ (L2) · Exit 9", rarity: "common", tags: ["street"],
    hours: { o: "12:00", c: "24:00" }, meal: "dinner", pick: true, why: "Youthful nightlife, buskers & street eats",
    blurb: "Art-school energy: indie music, buskers, thrift, clubs, street snacks and late-night everything.",
    tip: "Weekend street performances around the 'Hongdae playground' after dark." },
  { id: "yeonnam", n: "Yeonnam-dong 'Yeontral Park'", kr: "연남동", cat: "food", emoji: "🌳", lat: 37.5605, lng: 126.9250,
    area: "Mapo", subway: "Hongik Univ (L2) · Exit 3", rarity: "common", hours: { o: "11:00", c: "22:00" }, meal: "lunch",
    blurb: "Grassy former-railway park lined with brunch spots and small cafés.",
    tip: "Grab takeaway and picnic on the lawn — locals' weekend move. Great for brunch/lunch." },
  { id: "itaewon", n: "Itaewon", kr: "이태원", cat: "food", emoji: "🌍", lat: 37.5344, lng: 126.9948,
    area: "Yongsan", subway: "Itaewon (L6) · Exit 1-4", rarity: "common", hours: { o: "12:00", c: "24:00" }, meal: "dinner",
    blurb: "Seoul's most international quarter — global food, rooftop bars, vintage.",
    tip: "Hill up to Haebangchon (HBC) for views and craft beer. Best in the evening." },
  { id: "euljiro", n: "Euljiro Hipster Alleys", kr: "을지로", cat: "nightlife", emoji: "🍺", lat: 37.5660, lng: 126.9910,
    area: "Jung-gu", subway: "Euljiro 3-ga (L2/L3) · Exit 1", rarity: "rare", hours: { o: "17:00", c: "01:00" }, meal: "dinner",
    blurb: "By day a hardware district, by night hidden bars & 'nogari' beer alleys ('Hip-jiro').",
    tip: "Look for unmarked doors and upstairs bars. Manseon Hof for grilled pollack + beer. Evenings only." },
  { id: "seongsu", n: "Seongsu-dong", kr: "성수동", cat: "food", emoji: "☕", lat: 37.5445, lng: 127.0557,
    area: "Seongdong", subway: "Seongsu (L2) · Exit 3-4", rarity: "rare", tags: ["photo"],
    hours: { o: "10:00", c: "21:00" }, meal: "coffee", pick: true, why: "Seoul's coolest café & pop-up district",
    blurb: "The 'Brooklyn of Seoul' — repurposed factories now house Seoul's best cafés, pop-ups & flagship stores.",
    tip: "Café-hop the warehouse roasteries. Brand pop-ups here are the most photographed in the city." },
  { id: "garosugil", n: "Garosu-gil (Sinsa)", kr: "가로수길", cat: "shopping", emoji: "🌲", lat: 37.5203, lng: 127.0230,
    area: "Gangnam", subway: "Sinsa (L3) · Exit 8", rarity: "common", hours: { o: "11:00", c: "22:00" },
    blurb: "Ginkgo-lined boutique street in Gangnam — fashion flagships and cafés.",
    tip: "Slip into the quieter back alleys ('Serosu-gil') for indie shops." },
  { id: "gangnam", n: "Gangnam Station", kr: "강남역", cat: "shopping", emoji: "💼", lat: 37.4979, lng: 127.0276,
    area: "Gangnam", subway: "Gangnam (L2/Sinbundang)", rarity: "common", hours: { o: "10:00", c: "22:00" },
    blurb: "Glossy business-and-shopping core; giant underground mall beneath the crossroads.",
    tip: "The underground shopping arcade is a rainy-day maze of cheap fashion." },

  // ---------- COEX / ICML convention area ----------
  { id: "coex", n: "Starfield COEX Library", kr: "별마당 도서관", cat: "culture", emoji: "📚", lat: 37.5116, lng: 127.0596,
    area: "Gangnam", subway: "Samseong (L2) · Exit 5-6", rarity: "legendary", tags: ["photo"],
    hours: { o: "10:30", c: "22:00" }, pick: true, why: "The viral 13m-shelf library, 5 min from ICML",
    blurb: "Instagram-famous library with 13m-tall bookshelves, inside Asia's biggest underground mall.",
    tip: "Inside COEX, steps from the ICML halls — perfect between sessions. Free to enter." },
  { id: "bongeunsa", n: "Bongeunsa Temple", kr: "봉은사", cat: "culture", emoji: "🛕", lat: 37.5150, lng: 127.0577,
    area: "Gangnam", subway: "Bongeunsa (L9) · Exit 1", rarity: "rare", tags: ["photo"],
    hours: { o: "05:00", c: "21:00" }, pick: true, why: "A calm 1,200-yr temple right across from COEX",
    blurb: "1,200-year-old Buddhist temple sitting improbably beneath Gangnam skyscrapers — a photographer's contrast.",
    tip: "Directly across from COEX — a 10-min calm reset from the conference. Temple-stay & tea available." },
  { id: "apgujeong", n: "Apgujeong · Dosan Park", kr: "압구정 도산공원", cat: "shopping", emoji: "🕶️", lat: 37.5240, lng: 127.0360,
    area: "Gangnam", subway: "Apgujeong Rodeo (Sinbundang) · Exit 5", rarity: "common", tags: ["photo"], hours: { o: "11:00", c: "21:00" },
    blurb: "Seoul's luxury address: flagship boutiques, plastic-surgery row and dramatic concept cafés (Nudake).",
    tip: "Nudake's sculptural 'Peak' cake is a designed object as much as a dessert — pure photo bait." },

  // ---------- Design / museums / culture ----------
  { id: "ddp", n: "Dongdaemun Design Plaza (DDP)", kr: "DDP", cat: "culture", emoji: "🛸", lat: 37.5665, lng: 127.0092,
    area: "Jung-gu", subway: "DDP (L2/4/5) · Exit 1", rarity: "rare", tags: ["photo"],
    hours: { o: "10:00", c: "20:00" }, pick: true, why: "Zaha Hadid's neon spaceship — magic after dark",
    blurb: "Zaha Hadid's silver spaceship — design museum, exhibits and the glowing LED-rose garden.",
    tip: "Best after dark. The LED roses and curved façade are the money shots." },
  { id: "national-museum", n: "National Museum of Korea", kr: "국립중앙박물관", cat: "culture", emoji: "🏺", lat: 37.5240, lng: 126.9803,
    area: "Yongsan", subway: "Ichon (L4/Gyeongui) · Exit 2", rarity: "rare", hours: { o: "10:00", c: "18:00" },
    blurb: "Vast, free national museum — 5,000 years of Korean history, plus a reflecting-pool view of Namsan.",
    tip: "Don't miss the Pensive Bodhisattva gallery. Free admission; open Mon (closed some holidays)." },
  { id: "leeum", n: "Leeum Museum of Art", kr: "리움미술관", cat: "culture", emoji: "🎨", lat: 37.5385, lng: 126.9990,
    area: "Itaewon", subway: "Hangangjin (L6) · Exit 1", rarity: "rare", tags: ["booking"], hours: { o: "10:00", c: "18:00", x: [1] },
    blurb: "Samsung's flagship art museum — traditional Korean art + blue-chip contemporary, in a Koolhaas/Mario Botta building.",
    tip: "BOOK a timed slot online (free tickets go fast). Closed Mondays. Pair with Itaewon downhill." },
  { id: "war-memorial", n: "War Memorial of Korea", kr: "전쟁기념관", cat: "culture", emoji: "🎖️", lat: 37.5340, lng: 126.9773,
    area: "Yongsan", subway: "Samgakji (L4/L6) · Exit 12", rarity: "common", hours: { o: "09:30", c: "18:00", x: [1] },
    blurb: "Sweeping, free museum on the Korean War with an outdoor yard of tanks, jets and ships.",
    tip: "Big with kids. Allow 2 hours. Closed Mondays." },
  { id: "jogyesa", n: "Jogyesa Temple", kr: "조계사", cat: "culture", emoji: "🪷", lat: 37.5725, lng: 126.9820,
    area: "Jongno", subway: "Jonggak (L1) · Exit 2", rarity: "common", tags: ["photo"], hours: { o: "04:00", c: "21:00" },
    blurb: "The head temple of Korean Zen Buddhism — a splash of color and hanging lanterns downtown.",
    tip: "Spectacular under thousands of lotus lanterns around Buddha's Birthday (May)." },
  { id: "ihwa", n: "Ihwa Mural Village & Naksan Park", kr: "이화벽화마을", cat: "sight", emoji: "🖼️", lat: 37.5808, lng: 127.0074,
    area: "Jongno", subway: "Hyehwa (L4) · Exit 2", rarity: "common", tags: ["photo"], hours: { always: true },
    blurb: "Hillside village of murals and stairs along the old fortress wall, with wide city views.",
    tip: "The flower-stairs and angel-wings murals are the classic shots. It's residential — visit by day, keep quiet." },
  { id: "oiltank", n: "Oil Tank Culture Park", kr: "문화비축기지", cat: "culture", emoji: "🛢️", lat: 37.5697, lng: 126.8892,
    area: "Mapo", subway: "World Cup Stadium (L6) · Exit 2", rarity: "common", tags: ["photo"], hours: { o: "10:00", c: "18:00", x: [1] },
    blurb: "Decommissioned oil-storage tanks converted into raw, cavernous exhibition & performance spaces.",
    tip: "An industrial-chic photo playground; quiet on weekdays. Pair with Haneul Park's silver-grass fields nearby." },

  // ---------- Nature & rivers ----------
  { id: "namsan-park", n: "Namsan Park", kr: "남산공원", cat: "nature", emoji: "🌲", lat: 37.5509, lng: 126.9905,
    area: "Namsan", subway: "Myeongdong (L4) · Exit 3", rarity: "common", hours: { always: true },
    blurb: "Forested central mountain-park wrapping N Seoul Tower; easy trails right above downtown.",
    tip: "Walk up from Myeongdong; take the cable car or bus down." },
  { id: "seoul-forest", n: "Seoul Forest", kr: "서울숲", cat: "nature", emoji: "🦌", lat: 37.5443, lng: 127.0374,
    area: "Seongdong", subway: "Seoul Forest (Suin-Bundang) · Exit 4", rarity: "common", hours: { always: true },
    blurb: "Big riverside park with a deer enclosure, wetlands and lawns — next to Seongsu cafés.",
    tip: "Pair a morning here with an afternoon café crawl in Seongsu." },
  { id: "yeouido-park", n: "Yeouido Hangang Park", kr: "여의도 한강공원", cat: "nature", emoji: "🏞️", lat: 37.5285, lng: 126.9330,
    area: "Yeouido", subway: "Yeouinaru (L5) · Exit 2-3", rarity: "common", tags: ["photo"], hours: { always: true },
    blurb: "The classic Han River park — rent a bike, grab convenience-store ramyeon, watch the sunset over the water.",
    tip: "Order fried chicken to the riverbank via delivery like locals. Cherry blossoms in spring." },
  { id: "banpo", n: "Banpo Bridge Rainbow Fountain", kr: "반포대교 무지개분수", cat: "nature", emoji: "🌈", lat: 37.5100, lng: 126.9966,
    area: "Seocho", subway: "Express Bus Terminal (L3/7/9)", rarity: "rare", tags: ["photo"], hours: { always: true },
    pick: true, why: "The colored music-fountain show on the river",
    blurb: "The world's longest bridge fountain shoots colored water to music several nights a season.",
    tip: "Shows ~nightly in warm months around 19:30–21:00. Moonlight Rainbow Fountain — check the schedule." },
  { id: "seonyudo", n: "Seonyudo Park", kr: "선유도공원", cat: "nature", emoji: "🌿", lat: 37.5443, lng: 126.8975,
    area: "Yeongdeungpo", subway: "Seonyudo (L9) · Exit 2", rarity: "rare", tags: ["photo"], hours: { o: "06:00", c: "24:00" },
    blurb: "A former water-treatment plant on a Han River island, now an ivy-draped 'ecological garden of ruins'.",
    tip: "Cross the arched pedestrian bridge for skyline shots. One of Seoul's most photogenic quiet corners." },
  { id: "bukhansan", n: "Bukhansan National Park", kr: "북한산", cat: "nature", emoji: "⛰️", lat: 37.6586, lng: 126.9776,
    area: "Gangbuk", subway: "Gupabal (L3) → bus", rarity: "legendary", tags: ["photo"], hours: { o: "04:00", c: "18:00" },
    pick: true, why: "A real granite-peak hike inside the city",
    blurb: "A genuine granite mountain inside the city — Seoul's best hike and panorama.",
    tip: "Baegundae peak is the classic summit (~4-5h round trip). Go early; wear real shoes. Hours vary by season." },

  // ---------- Markets & food ----------
  { id: "gwangjang", n: "Gwangjang Market", kr: "광장시장", cat: "food", emoji: "🥟", lat: 37.5701, lng: 126.9997,
    area: "Jongno", subway: "Jongno 5-ga (L1) · Exit 8", rarity: "legendary", tags: ["street", "photo"],
    hours: { o: "09:00", c: "23:00" }, meal: "both", pick: true, why: "The city's ultimate street-food crawl",
    blurb: "Seoul's iconic street-food market: mung-bean bindaetteok, mayak gimbap, live octopus, raw beef.",
    tip: "Go hungry, bring cash, point-and-eat at the stools. Busiest — and most photogenic — at dusk." },
  { id: "tongin", n: "Tongin Market (Token Lunchbox)", kr: "통인시장", cat: "food", emoji: "🪙", lat: 37.5806, lng: 126.9705,
    area: "Jongno", subway: "Gyeongbokgung (L3) · Exit 2", rarity: "rare", tags: ["street"],
    hours: { o: "07:00", c: "18:00", x: [1] }, meal: "lunch",
    blurb: "A local market with a twist: buy brass tokens, then fill an empty lunchbox from the street-food stalls.",
    tip: "Buy tokens at the info center (token café ~11:00–16:00); the oil-tteokbokki is the signature. A lunch thing." },
  { id: "sindang", n: "Sindang Tteokbokki Town", kr: "신당동 떡볶이 골목", cat: "food", emoji: "🌶️", lat: 37.5658, lng: 127.0186,
    area: "Jung-gu", subway: "Sindang (L2/L6) · Exit 8", rarity: "common", tags: ["street"],
    hours: { o: "11:00", c: "23:00" }, meal: "both",
    blurb: "The alley that made 'jjukkumi/rabokki' famous — bubbling pans of tteokbokki with noodles, egg and dumplings.",
    tip: "'Masitnun Tteokbokki' & Aefawon are the old-school picks. Order a shared pan and let it simmer." },
  { id: "namdaemun", n: "Namdaemun Market", kr: "남대문시장", cat: "shopping", emoji: "🧦", lat: 37.5591, lng: 126.9779,
    area: "Jung-gu", subway: "Hoehyeon (L4) · Exit 5", rarity: "common", tags: ["street"],
    hours: { o: "08:00", c: "22:00" }, meal: "lunch",
    blurb: "Korea's oldest & largest market — everything from kitchenware to kids' clothes, plus hearty food alleys.",
    tip: "Find 'Galchi jorim alley' for braised hairtail stew and the famous hotteok carts." },
  { id: "noryangjin", n: "Noryangjin Fish Market", kr: "노량진수산시장", cat: "food", emoji: "🦑", lat: 37.5138, lng: 126.9407,
    area: "Dongjak", subway: "Noryangjin (L1/L9) · Exit 1", rarity: "rare", hours: { always: true }, meal: "dinner",
    blurb: "Cavernous seafood market — pick your fish downstairs, have it served hoe (raw) upstairs.",
    tip: "Open around the clock. Prices are negotiable; agree the total (fish + serving fee) before they cut. A dinner feast." },
  { id: "tosokchon", n: "Tosokchon Samgyetang", kr: "토속촌 삼계탕", cat: "food", emoji: "🍲", lat: 37.5779, lng: 126.9718,
    area: "Jongno", subway: "Gyeongbokgung (L3) · Exit 2", rarity: "common", hours: { o: "10:00", c: "22:00" }, meal: "lunch",
    pick: true, why: "Legendary ginseng chicken soup by the palace",
    blurb: "The famous ginseng chicken soup house near the palace — a whole young chicken stuffed with rice.",
    tip: "Expect a queue at lunch; it moves fast. Perfect warm lunch after Gyeongbokgung." },
  { id: "myeongdong-kyoja", n: "Myeongdong Kyoja", kr: "명동교자", cat: "food", emoji: "🍜", lat: 37.5631, lng: 126.9853,
    area: "Jung-gu", subway: "Myeongdong (L4) · Exit 8", rarity: "common", hours: { o: "10:30", c: "21:30" }, meal: "both",
    blurb: "One dish done perfectly: knife-cut noodle soup (kalguksu) with garlicky dumplings. Michelin Bib Gourmand.",
    tip: "The complimentary kimchi is famously fiery and bottomless. Quick lunch or early dinner." },
  { id: "mapo-galbi", n: "Mapo Jeong Daepo (BBQ)", kr: "마포 정대포", cat: "food", emoji: "🥩", lat: 37.5430, lng: 126.9490,
    area: "Mapo", subway: "Gongdeok (L5/6) · Exit 8", rarity: "common", hours: { o: "11:30", c: "23:00" }, meal: "dinner",
    blurb: "Classic smoky Korean BBQ — thick pork galbi over charcoal, spicy 'galmaegisal' skirt.",
    tip: "A dinner-and-soju institution. Order the seasoned galbi. Grill smell in your clothes = doing it right." },
  { id: "onion-anguk", n: "Café Onion Anguk", kr: "어니언 안국", cat: "food", emoji: "🥐", lat: 37.5760, lng: 126.9857,
    area: "Jongno", subway: "Anguk (L3) · Exit 3", rarity: "rare", tags: ["photo"], hours: { o: "09:00", c: "22:00" }, meal: "coffee",
    blurb: "A restored hanok courtyard café famous for its snow-sugar 'pandoro' pastry.",
    tip: "Go mid-morning for coffee; the pandoro sells out. The sugar-dusted pastry in the hanok is the shot. Near Bukchon." },
  { id: "mangwon", n: "Mangwon Market", kr: "망원시장", cat: "food", emoji: "🍢", lat: 37.5556, lng: 126.9016,
    area: "Mapo", subway: "Mangwon (L6) · Exit 2", rarity: "common", tags: ["street"], hours: { o: "10:00", c: "22:00" }, meal: "both",
    blurb: "A beloved, un-touristy local market — cheap tteokbokki, fried snacks, chicken and dumplings.",
    tip: "Walk it off toward the Han River at Mangwon Hangang Park." },
  { id: "commonground", n: "Common Ground", kr: "커먼그라운드", cat: "shopping", emoji: "📦", lat: 37.5410, lng: 127.0700,
    area: "Gwangjin", subway: "Konkuk Univ (L2/L7) · Exit 6", rarity: "common", tags: ["photo"], hours: { o: "11:00", c: "22:00" },
    blurb: "The world's largest shipping-container mall — indie fashion, food trucks and pop-ups in cobalt-blue boxes.",
    tip: "Good rainy-plan near Seongsu; the blue containers at night are photogenic." },
  { id: "hyundai-seoul", n: "The Hyundai Seoul (Sounds Forest)", kr: "더현대 서울", cat: "shopping", emoji: "🪴", lat: 37.5259, lng: 126.9285,
    area: "Yeouido", subway: "Yeouido (L5/L9) · Exit 3", rarity: "rare", tags: ["photo"], hours: { o: "10:30", c: "20:00" },
    pick: true, why: "A glass-roofed indoor forest mall — perfect if it rains",
    blurb: "A jaw-dropping department store built around a glass-roofed indoor garden with a 12m waterfall.",
    tip: "Head to the 5th-floor 'Sounds Forest' green atrium. The basement food hall is a feast. Fully indoor — rain-proof plan." },
  { id: "dongdaemun-night", n: "Dongdaemun Night Markets", kr: "동대문", cat: "shopping", emoji: "🌃", lat: 37.5670, lng: 127.0090,
    area: "Jung-gu", subway: "Dongdaemun (L1/L4) · Exit 8", rarity: "common", hours: { o: "10:30", c: "05:00" },
    blurb: "Wholesale fashion towers (Doota, Migliore) that stay open through the night.",
    tip: "Peaks after midnight. Pair with DDP right next door." }
];

/* Best time of day per place — powers the 🌅 Morning / ☀️ Afternoon / 🌙 Evening
 * filter + badge. Places that are good anytime get all three. */
(function () {
  var T = {
    gyeongbokgung: ["morning"], changdeokgung: ["morning"], deoksugung: ["afternoon", "evening"],
    nseoultower: ["evening"], lotteworldtower: ["afternoon", "evening"], cheonggyecheon: ["evening"],
    gwanghwamun: ["morning", "afternoon"], seoullo: ["evening"], bukchon: ["morning"], insadong: ["afternoon"],
    ikseondong: ["evening"], myeongdong: ["evening"], hongdae: ["evening"], yeonnam: ["morning", "afternoon"],
    itaewon: ["evening"], euljiro: ["evening"], seongsu: ["afternoon"], garosugil: ["afternoon"],
    gangnam: ["afternoon", "evening"], coex: ["afternoon"], bongeunsa: ["morning"], apgujeong: ["afternoon"],
    ddp: ["evening"], "national-museum": ["afternoon"], leeum: ["afternoon"], "war-memorial": ["afternoon"],
    jogyesa: ["morning"], ihwa: ["afternoon"], oiltank: ["afternoon"], "namsan-park": ["morning", "afternoon"],
    "seoul-forest": ["morning", "afternoon"], "yeouido-park": ["evening"], banpo: ["evening"], seonyudo: ["afternoon"],
    bukhansan: ["morning"], gwangjang: ["afternoon", "evening"], tongin: ["morning", "afternoon"], sindang: ["evening"],
    namdaemun: ["morning", "afternoon"], noryangjin: ["evening"], tosokchon: ["afternoon"], "myeongdong-kyoja": ["afternoon"],
    "mapo-galbi": ["evening"], "onion-anguk": ["morning"], mangwon: ["afternoon", "evening"],
    commonground: ["afternoon", "evening"], "hyundai-seoul": ["afternoon"], "dongdaemun-night": ["evening"]
  };
  window.SEOUL_PLACES.forEach(function (p) { p.time = T[p.id] || ["morning", "afternoon", "evening"]; });
})();
